<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.csapi.org/wsdl/parlayx/data/sync/v1_0/service" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://www.csapi.org/wsdl/parlayx/data/sync/v1_0/interface" name="dataService" targetNamespace="http://www.csapi.org/wsdl/parlayx/data/sync/v1_0/service">
    <wsdl:import location="./sdp-included.wsdl" namespace="http://www.csapi.org/wsdl/parlayx/data/sync/v1_0/interface"> </wsdl:import>
    <wsdl:binding name="dataServiceSoapBinding" type="ns1:DataSync">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="syncOrderRelation">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="syncOrderRelation">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="syncOrderRelationResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="syncSubscriptionData">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="syncSubscriptionData">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="syncSubscriptionDataResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="syncMSISDNChange">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="syncMSISDNChange">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="syncMSISDNChangeResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="syncSubscriptionActive">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="syncSubscriptionActive">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="syncSubscriptionActiveResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="changeMSISDN">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="changeMSISDN">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="changeMSISDNResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="dataService">
        <wsdl:port binding="tns:dataServiceSoapBinding" name="dataPort">
            <soap:address location="http://0.0.0.0:8080/sdp/data"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>